# CI steps for all branches:
-
  version: 1.0.{build}
  assembly_info:
    patch: false
  build_script:
    build.cmd version="{version}"
  test: off

# For master only:
-
  branches:
    only:
      - master

  deploy_script:
    build.cmd "PublishNugetPackage" -st nugetKey=%nugetKey% version="{version}"
